### ISSUE TITLE
convolution kernel size

### ISSUE THREAD

**Issue by rqthqwipeh134** [thanh-guong/master-thesis#3]
Excuse me, why does (conv(16,4),conv(32,2)) perform better than (conv(256,(1,3)),conv(80,(2,3)))? In this field , I have not seen the convolution kernel size is even. Does it make sense?

**Comment by thanh-guong** [comment]
Hi there, thanks for the good question.

The neural networks you see are the result of experiments I did **tuning** the kernel sizes and number of filters employed in each convolutional layer.
I received a few hints to improve performances by tuning those values, you can see all in [this](https://datascience.stackexchange.com/questions/100674/convolutional-neural-network-low-performance) DataScience StackExchange Q/A.

The input size is 2x128, so I thought that a 2x2 filter (that **fits the size** of the 2x128 matrix) would perform better than other ones. The value for the kernel size of the second convolutional layer (4x4) just came from tuning the values, train the neural network, interpretating the results and then choosing next values to test. I don't have an answer why even kernel sized filters perform better in this case, but results tells that they actually do.
