### ISSUE TITLE
Where can I read your paper?

### ISSUE THREAD

**Issue by aiyunhug** [thanh-guong/master-thesis#4]

**Comment by thanh-guong** [comment]
Hi there, thanks for your interest in my work.

The paper was submitted to the conference _IWSDA'2022: The 10th International Conference on Signal Design and its Applications in Communication_ in Colchester, UK, August 1-5, 2022. I can't publish the paper before the conference date, but I will publish it after.

**Comment by thanh-guong** [comment]
Hi, I finally can give you a link: https://ieeexplore.ieee.org/document/9870449
