### ISSUE TITLE
Classification time performances

### ISSUE THREAD

**Issue by guet-clg** [thanh-guong/master-thesis#5]
How long will it take the system to detect an unknown signal when it suddenly appears? Will it shorten the detection time if it reappears?

**Comment by thanh-guong** [comment]
Hi, thanks for your question.

We didn't test classification time performances after the model training.
Classification time will not decrease if a signal reappears. This is because, once model training is complete, weights are never modified.

**Comment by guet-clg** [comment]
Thank! And the following error occurs when running dataset_expansion.ipynb. How to solve it? Last Can you tell me how to run the program to get the result graph in the paper?
SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_df[dft_signals_column_dataframe_name] = transformed_signals

**Comment by thanh-guong** [comment]
If you have got an error, can you post the full stack trace, and the code which gave that error?

**Comment by guet-clg** [comment]
Is it running under Linux or Windows?

**Comment by thanh-guong** [comment]
I ran it only on Windows.

**Comment by guet-clg** [comment]
Thank you, I'm very sorry for asking many small questions.

**Comment by thanh-guong** [comment]
No problems, I'm here for this 😁
