### ISSUE TITLE
  Operation steps

### ISSUE THREAD

**Issue by guet-clg** [thanh-guong/master-thesis#6]
Can you tell me how to run the program to get the result graph in the paper?

**Comment by thanh-guong** [comment]
### Execution steps

As written in the README.MD your GPU has to be an nVIDIA GPU, and you have to execute the following steps:

- Download the dataset [here](https://www.deepsig.ai/datasets). Extract the dataset in a directory named data/. Dataset file should has to be named RML2016.10a_dict.pkl.
- You need to have Python (at least 3.9.x) and pip (included with Python) installed on your system.
- You need to run pip install -r requirements.txt to install this project dependencies.
- You need to install CUDA Toolkit in your System: [download](https://developer.nvidia.com/cuda-toolkit).
- You need to install cuDNN Library in your System: [download](https://developer.nvidia.com/rdp/cudnn-download) and follow NVDIA [installation guide](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html)

Then you can install Jupyter Notebook from [here](https://jupyter.org/), and execute the single .ipynb notebooks inside the directories in the repository.

### Results

The best results obtained, described in the paper, are obtained by executing [FreeHandV3](https://github.com/thanh-guong/master-thesis/blob/main/IQ%20-%20Data%20Augmentation/rotate/85-perc-train/FreeHandV3_rotation.ipynb)

**Comment by guet-clg** [comment]
Thanks for your detailed reply!
